### ISSUE TITLE
Implement basic Template functions

### ISSUE THREAD

**Issue by raeon** [OldaranT/EllirionBuildFramework#20]
## Templates
Templates are a collection of block data representing an area in a world. This area could for example contain a building. These templates can be created from existing structures in a world, or can be placed inside a world to easily "copy and paste" structures or terrain. The Templates consist of two main components, described below.

### Tasks
- [x] Create base class
- [x] Input data from world
- [x] Ouptut data to world
- [x] Convert to BoundingBox (requires #10)
- [x] Serialize to disk
- [x] Deserialize from disk
