### ISSUE TITLE
Path finder

### ISSUE THREAD

**Issue by raeon** [OldaranT/EllirionBuildFramework#3]
# Graph (#17)
Implement a generic Graph class.

# Path finder
In order to support the construction of paths (roads) between buildings, an atypical path finder is required. This path finder is tasked with finding a path which has a predetermined width/height and optionally additional limitations such as maximum ascension per horizontal distance. The turning radius of this path may also be limited by the tileset used by the path builder.

# Tasks
- [ ] Determine path from point A to B
- [ ] Ensure path has minimal width/height
- [ ] Ensure path does not build excessive bridges or floating stairs
- [ ] Ensure path stays as close to ground as possible when applicable
- [ ] Ensure path does not exceed dynamic limits of bridge length
- [ ] Output a Graph of path nodes

**Note:** the above 'ensure' tasks should happen *during* the path determining, not afterwards.
