### ISSUE TITLE
Path builder

### ISSUE THREAD

**Issue by raeon** [OldaranT/EllirionBuildFramework#4]
# Graph (#17)
Implement a generic Graph class.

# Path builder
Given a graph produced by the path finder, the path builder should use a given tileset provider to construct a path along the nodes of the graph. There should be additional care put into the construction of floating structures and their corresponding realistic supports.

## Tasks
- [x] Take a path as input
- [x] Place tiles along the path 
- [x] Build supports for when the path goes through the air
- [x] Build steps so the path can be walked along
