### ISSUE TITLE
Display Template as hologram

### ISSUE THREAD

**Issue by raeon** [OldaranT/EllirionBuildFramework#6]
Requires #1 to be resolved.

## Hologram
A hologram is a transformed version of a template used to show the template to a user in a clear manner. Blocks are shown in the corners of the template. Markers are shown using a different type of block. Existing blocks at the location of the hologram are projected as invisible or colored transparent blocks.

# Tasks
- [x] Create a hologram template from a regular template
- [x] Include real world blocks in the hologram as a transparent block (glass, barrier)
- [x] Show markers in the hologram
- [x] Track what holograms are viewed by what players at the current point in time
- [x] Send a hologram to a player for viewing
- [x] Send real data to a player to hide the hologram
