### ISSUE TITLE
Add Markers to Templates

### ISSUE THREAD

**Issue by chrisstar321** [OldaranT/EllirionBuildFramework#7]
## Markers
A marker is an unique named position within the Template area. An example of this could be a marker "path" that specifies where pathing should connect to this Template.

### Tasks
- [x] Adding marker (name, pos) to template
- [x] Find a marker (name) from template
- [x] Removing marker (name) from template
- [x] Serialize to disk
- [x] Deserialize from disk
