### ISSUE TITLE
Validate terrain before correction

### ISSUE THREAD

**Issue by OldaranT** [OldaranT/EllirionBuildFramework#8]
## Validation
Before planning the alteration of any terrain, it should be ensured that the required correction will be within acceptable ranges.

### Tasks
- [x] Verify bounding box is not floating
- [x] Verify bounding box is mostly connected to the ground (e.g. 75%)
- [x] Verify bounding box is not sandwiched (must have space above it)
- [x] Verify amount of changed blocks does not exceed a dynamic threshold
- [x] Verify there is no liquid on top of, next to or inside of the bounding box
