### ISSUE TITLE
Correct terrain based on bounding box

### ISSUE THREAD

**Issue by chrisstar321** [OldaranT/EllirionBuildFramework#9]
## Correction
After the validation stage (#8), correction may begin.

### Tasks
- [x] Flatten the floor below the (optionally specified, otherwise use the bounding box bottom)
- [x] Blend the cross-over from the surrounding terrain to the flattened area
- [x] Flatten the terrain if smal holes are present at the side of the boundingbox
- [x] Build supporting structures under floating parts of the flattened area
